import { languageMap } from "../utils/translate";
import { getURL } from "../utils/helpers";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        {/*{Object.keys(languageMap)*/}
        {/*  .filter((lang) => lang !== language)*/}
        {/*  .map((lang) => (*/}
        {/*    <link*/}
        {/*      key={lang}*/}
        {/*      rel="alternate"*/}
        {/*      hrefLang={lang}*/}
        {/*      href={`${getURL()}/${lang}${router.asPath}`}*/}
        {/*    />*/}
        {/*  ))}*/}
      </Head>
      <body>{children}</body>
    </html>
  );
}
